### ISSUE TITLE
fix: List types

### ISSUE THREAD

**Issue by matthprost** [scaleway/ultraviolet#1782]

**Comment by baptisteArno** [comment]
`SelectBar` > `selectedItems` doesn't have the right type `Record<string, unknown>[]`, should be `T[]` where T is the type passed to `List` component

**Comment by baptisteArno** [comment]
Is there anything else?

> `SelectBar` > `selectedItems` doesn't have the right type: `Record<string, unknown>[]`, should be `T[]` where T is the type passed to `List` component

This was fixed on #1901

**Comment by chambo-e** [comment]
@DorianMaliszewski @matthprost this has been fixed by ListV2 right ?

**Comment by baptisteArno** [comment]
Yes! 👌

**Comment by matthprost** [comment]
@chambo-e I will wait for ListV2 to become List once migration is done I will close this issue, same for pagination 😄
