### ISSUE TITLE
[Bug]: List checkbox doesn't update state each click

### ISSUE THREAD

**Issue by DorianMaliszewski** [scaleway/ultraviolet#4618]
### Is it Front-End or Design related only?

Front-End

### Library

UI

### Current Behavior

Actually, when clicking on a checkbox in the List (since React 19) there are sometimes the checkbox doesn't update its state. On my video I put a plugin on mouse click (Red reverb), as you can see there are some clicks that don't trigger the update (Notable example between 0:18 and 0:24)

https://github.com/user-attachments/assets/023c256a-42ff-4c96-a63c-bf523c236e06

### Expected Behavior

Each time a click happen it should update the state of the checkbox as it was with React 18

### Context

Was diving into a problem when updating on internal console to React 19. You can see the bug when ordering a Domain by playing with checkboxes on the first step of the form

**Comment by philibea** [comment]
> ### Is it Front-End or Design related only?
> Front-End
> 
> ### Library
> UI
> 
> ### Current Behavior
> Actually, when clicking on a checkbox in the List (since React 19) there are sometimes the checkbox doesn't update its state. On my video I put a plugin on mouse click (Red reverb), as you can see there are some clicks that don't trigger the update (Notable example between 0:18 and 0:24)
> 
>  20241224_110603.mp4 
> ### Expected Behavior
> Each time a click happen it should update the state of the checkbox as it was with React 18
> 
> ### Context
> Was diving into a problem when updating on internal console to React 19. You can see the bug when ordering a Domain by playing with checkboxes on the first step of the form



I made a quick with playwright to see this issue https://github.com/scaleway/ultraviolet/pull/4619
